### ISSUE TITLE
Site breakage: granit.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/autoconsent#200]
## Description
https://www.granit.com/se/ - gray overlay stays over the site after popup is dismissed.

The popup on [site]
 - [ ] is not detected
 - [x] is not dismissed properly
 - [ ] other (elaborate below)

**Tested on**
 - [x] DuckDuckGo macOS browser
 - [ ] DuckDuckGo Windows browser
 - [ ] DuckDuckGo Android browser
 - [ ] DuckDuckGo iOS browser
 - [x] Chrome browser extension
 - [ ] Firefox browser extension

**Tested from country**: DE

**Autoconsent version**: 4.3.3

**Screenshot (optional)**

**Comment by muodov** [comment]
This was fixed in https://github.com/duckduckgo/autoconsent/pull/211
