### ISSUE TITLE
Re-use autoconsent in Puppeteer headless

### ISSUE THREAD

**Issue by wurst-hans** [duckduckgo/autoconsent#39]
I've written a simple NodeJS script for some web tests using a headless Puppeteer. My challenge now is to confirm consent banners (CMP). I've seen, that there is a release 1.0.8 which has a ready-to-run JS for Puppeteer in `dist` folder, but that seems quite old (i.e. `rules.json` of release 3.0.0 is much larger).

When trying to include CJS file, like:

```
const autoConsent = require('@duckduckgo/autoconsent/dist/autoconsent.cjs.js');
```

NodeJS throws an error:

```
/mnt/myproject/node_modules/@duckduckgo/autoconsent/dist/autoconsent.cjs.js:14
  [full minified JS code is printed here]
                                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/myproject/resources/nodejs/check.js:19:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

The problem is, that Puppeteer in headless mode is not able to run browser extensions, so I can't use the MV3 extension.
Please note that I'm not a NodeJS pro, but I want to know if there is a way to implement the current autoconsent 3.0.0 in my JS script?

**Comment by muodov** [comment]
Hi @wurst-hans, this is definitely possible, but you will need to write some code. Basically, you'll need to inject a content script into the page (you can use `dist/autoconsent.playwright.js`) and implement (parts of) the logic that is done by the extension's background script. That is, you'll need to respond to [messages](https://github.com/duckduckgo/autoconsent/blob/main/api.md) from the content script.

There are two places you can look for reference: we are doing pretty much the same thing in [Playwright test runner](https://github.com/duckduckgo/autoconsent/blob/main/playwright/runner.ts) in this repo and in the [Puppeteer-based crawler](https://github.com/duckduckgo/tracker-radar-collector/blob/main/collectors/CMPCollector.js). Depending on your needs, you may get away with much less code though.

Alternatively, if you are building against specific scenarios, you can import the [Autoconsent](https://github.com/duckduckgo/autoconsent/blob/main/lib/web.ts#L12) class directly and instrument it in your own content script that would not need any communication with the background script.

I hope this helps!
