### ISSUE TITLE
Site breakage: thefreeaudit.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/autoconsent#74]
## Description

The popup on https://thefreeaudit.com/
 - [ ] is not detected
 - [ ] is not dismissed properly
 - [x] other (elaborate below)
Breaks the site submission form on the page after opt-out.

**Tested on**
 - [x] DuckDuckGo macOS browser
 - [x] DuckDuckGo Windows browser
 - [ ] DuckDuckGo Android browser
 - [ ] DuckDuckGo iOS browser
 - [ ] Chrome browser extension
 - [ ] Firefox browser extension

**Tested from country**: DE

**Autoconsent version**: 3.0.4

**Screenshot (optional)**

**Comment by muodov** [comment]
Some context: the popup doesn't have an option for rejecting. The submission form is also broken if you simply ignore the popup.

**Comment by sammacbeth** [comment]
Seems to be working now.
